const INCREASE = 'INCREASE'
const DECREASE = 'DECREASE'
const REMOVE = 'REMOVE'
const CLEAR_CART = 'CLEAR_CART'
const GET_TOTALS = 'GET_TOTALS'
const TOGGLE_AMOUNT = 'TOGGLE_AMOUNT'
export { INCREASE, DECREASE, REMOVE, CLEAR_CART, GET_TOTALS, TOGGLE_AMOUNT }
